--liquibase formatted sql

--changeset llefevre:9 dbms:oracle
CREATE TABLE customers (
  id number generated by default as identity (cache 100) primary key, -- auto generated identifier if *not* specified
  first_name varchar2(100) not null,
  last_name  varchar2(100) not null,
  country varchar2(100) not null
);

insert into customers (id, first_name, last_name, country)
    values (465, 'Elena', 'Cortes', 'Spain');
insert into customers (id, first_name, last_name, country)
    values (10408, 'Jean', 'Martin', 'Luxembourg');
insert into customers (id, first_name, last_name, country)
    values (503, 'Luca', 'Armani', 'Italy');
insert into customers (id, first_name, last_name, country)
    values (415981, 'Nicolas', 'Le Jardinier', 'France');
commit;
--rollback drop table customers purge;

--changeset llefevre:10 dbms:oracle
-- Create the table containing countries VAT
CREATE TABLE country_taxes (
   country_name VARCHAR2(100) NOT NULL PRIMARY KEY,
   tax NUMBER(6,3) DEFAULT 0.05 NOT NULL
);

-- Inserting some values
INSERT INTO country_taxes (country_name, tax) VALUES ('Luxembourg', 0.17);
INSERT INTO COUNTRY_TAXES (COUNTRY_NAME, TAX) VALUES ('Italy',      0.22);
INSERT INTO COUNTRY_TAXES (COUNTRY_NAME, TAX) VALUES ('France',     0.2 );
INSERT INTO COUNTRY_TAXES (COUNTRY_NAME, TAX) VALUES ('Spain',      0.21);
commit;
--rollback drop table country_taxes purge;
